version: '3'
services:
#  app:
#    image: 'library-elastic:latest'
#    build:
#      dockerfile: devops/Dockerfile
#      context: ../
#
#    container_name: library-elastic
#    ports:
#      - 8080:8081
#    depends_on:
#      - elasticsearch
#    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
    ports:
      - 9200:9200